### ISSUE TITLE
Add MaterialUI

### ISSUE THREAD

**Issue by raae** [olavea/pow-site#3]
- [x] I think we should focus on getting the structure and functionality  correct for the site. 
- [x] Then I can add in MaterialUI.
- [x] customize mui, check out the [queen site](https://github.com/raae/queen.raae.codes/tree/main/src/%40raae/gatsby-theme-mui).

**Comment by raae** [comment]
I created a plugin so this taks is up for grabs @olavea.

The plugin is [@raae/gatsby-theme-mui](https://www.npmjs.com/package/@raae/gatsby-theme-mui). To see how to customize it check out the [queen site](https://github.com/raae/queen.raae.codes/tree/main/src/%40raae/gatsby-theme-mui).
